name: Deploy on GH Pages

on:
  push:
    branches:
    - gh-pages
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Use Node.js '12.x'
      uses: actions/setup-node@v4
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm install --global rollup@2.79.1
    - run: export BASEPATH='/WAI/eval/report-tool' && npm run clean:build && rollup -c
    - run: cd build && ln -s index.html 404.html # symlink for GH pages fallback
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        BRANCH: gh-pages
        FOLDER: build
    - name: Create zip file 🗂
      uses: papeloto/action-zip@v1
      with:
        files: build/
        dest: result.zip 
